f ($valor >= 15) {
    //... trata para idade maior ou igual a 15 ... 
} else if ($valor >= 10 && $valor < 15) {
    //... trata para idade entre 10 e 14 anos ...
} else if ($valor >= 5 && $valor < 10) {
    //... trata para idade entre 5 e 9 anos ...
} else {
    // ... trata para idade inferior a 5 anos ...
}

//https://pt.stackoverflow.com/q/357611/101
