for (int a = 0, b = 0; a < 10 && b < 20; a++, b++)
    listaA[a] ...
    listaB[b] ...


for (int a = 0, b = 0; a < 10 && b < 10; a++, b++)
    listaA[a] ...
    listaB[b] ...

for (int a = 0; a < 10; a++)
    listaA[a] ...
    listaB[a] ...
    
//https://pt.stackoverflow.com/q/286391/101
