<ItemGroup>
  <Using Remove="System.Net.Http" />
</ItemGroup>

<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
...
<ImplicitUsings>disable</ImplicitUsings>
</PropertyGroup>

</Project>

<ItemGroup>
    <Using Include="SuperheroApp.Models"/>
    <Using Include="System.Console" Static="True" />
    <Using Include="System.DateTime" Alias="DT" />
</ItemGroup>

// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;

//https://pt.stackoverflow.com/q/576320/101
